export const Classes = [
  {
    course_id: "C001",
    course_name: "Introduction to Web Development",
    course_description: "Learn the basics of web development including HTML, CSS, and JavaScript.",
    course_studentcount: 150,
    course_provider: "Harvard University",
    course_provimg: null,
    course_category: "Web Development",
    course_price: 49.99,
    course_durationstart: "2024-05-01",
    course_durationend: "2024-06-30",
    course_rating: 4.5,
    course_level: "Beginner",
    course_avgtime: "2 hours per week",
    instructor_id: "00001"
  },
  {
    course_id: "C002",
    course_name: "Data Science Fundamentals",
    course_description: "Discover the fundamentals of data science including data analysis, machine learning, and statistical modeling.",
    course_studentcount: 120,
    course_provider: "Stanford University",
    course_provimg: null,
    course_category: "Data Science",
    course_price: 69.99,
    course_durationstart: "2024-06-15",
    course_durationend: "2024-08-15",
    course_rating: 4.8,
    course_level: "Intermediate",
    course_avgtime: "3 hours per week",
    instructor_id: "00002"
  },
  {
    course_id: "C003",
    course_name: "Introduction to Python Programming",
    course_description: "Master the basics of Python programming language.",
    course_studentcount: 100,
    course_provider: "MIT",
    course_provimg: null,
    course_category: "Programming",
    course_price: 29.99,
    course_durationstart: "2024-07-01",
    course_durationend: "2024-08-31",
    course_rating: 4.3,
    course_level: "Beginner",
    course_avgtime: "1.5 hours per week",
    instructor_id: "00003"
  },
  {
    course_id: "C004",
    course_name: "Financial Accounting Principles",
    course_description: "Learn the fundamental principles of financial accounting.",
    course_studentcount: 80,
    course_provider: "University of Chicago",
    course_provimg: null,
    course_category: "Finance",
    course_price: 59.99,
    course_durationstart: "2024-06-01",
    course_durationend: "2024-07-31",
    course_rating: 4.6,
    course_level: "Intermediate",
    course_avgtime: "2.5 hours per week",
    instructor_id: "00004"
  },
  {
    course_id: "C005",
    course_name: "Artificial Intelligence Ethics",
    course_description: "Explore the ethical considerations in artificial intelligence and machine learning.",
    course_studentcount: 90,
    course_provider: "Columbia University",
    course_provimg: null,
    course_category: "Artificial Intelligence",
    course_price: 79.99,
    course_durationstart: "2024-07-15",
    course_durationend: "2024-09-15",
    course_rating: 4.7,
    course_level: "Advanced",
    course_avgtime: "2 hours per week",
    instructor_id: "00005"
  },
  {
    course_id: "C006",
    course_name: "Java Programming Masterclass",
    course_description: "Become proficient in Java programming language with hands-on exercises and projects.",
    course_studentcount: 110,
    course_provider: "MIT",
    course_provimg: null,
    course_category: "Programming",
    course_price: 79.99,
    course_durationstart: "2024-08-01",
    course_durationend: "2024-10-01",
    course_rating: 4.4,
    course_level: "Intermediate",
    course_avgtime: "3 hours per week",
    instructor_id: "00006"
  },
  {
    course_id: "C007",
    course_name: "Machine Learning Foundations",
    course_description: "Build a solid foundation in machine learning concepts and algorithms.",
    course_studentcount: 130,
    course_provider: "University of California, Berkeley",
    course_provimg: null,
    course_category: "Machine Learning",
    course_price: 89.99,
    course_durationstart: "2024-08-15",
    course_durationend: "2024-10-15",
    course_rating: 4.6,
    course_level: "Intermediate",
    course_avgtime: "3 hours per week",
    instructor_id: "00007"
  },
  {
    course_id: "C008",
    course_name: "Digital Marketing Strategies",
    course_description: "Learn effective digital marketing strategies for businesses of all sizes.",
    course_studentcount: 140,
    course_provider: "Wharton School, University of Pennsylvania",
    course_provimg: null,
    course_category: "Marketing",
    course_price: 99.99,
    course_durationstart: "2024-09-01",
    course_durationend: "2024-11-01",
    course_rating: 4.7,
    course_level: "Intermediate",
    course_avgtime: "2.5 hours per week",
    instructor_id: "00008"
  },
  {
    course_id: "C009",
    course_name: "Cybersecurity Fundamentals",
    course_description: "Gain a comprehensive understanding of cybersecurity fundamentals and best practices.",
    course_studentcount: 100,
    course_provider: "ETH Zurich",
    course_provimg: null,
    course_category: "Cybersecurity",
    course_price: 79.99,
    course_durationstart: "2024-09-15",
    course_durationend: "2024-11-15",
    course_rating: 4.5,
    course_level: "Intermediate",
    course_avgtime: "2 hours per week",
    instructor_id: "00009"
  },
  {
    course_id: "C010",
    course_name: "Advanced Excel Techniques",
    course_description: "Master advanced Excel techniques to streamline data analysis and visualization.",
    course_studentcount: 120,
    course_provider: "Microsoft",
    course_provimg: null,
    course_category: "Data Analysis",
    course_price: 49.99,
    course_durationstart: "2024-10-01",
    course_durationend: "2024-12-01",
    course_rating: 4.6,
    course_level: "Advanced",
    course_avgtime: "2.5 hours per week",
    instructor_id: "00010"
  }
]
